name: Build Website Data

on:
  workflow_dispatch:

  push:
    paths:
      - "data/**"
      - "web/build.py"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Builder
        run: |
          python web/build.py

      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add output

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update website data"
            git push
          fi
