name: Run Semagram Scraper

on:
  schedule:
    - cron: '0 0,5,10,15,20,23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-chromium

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright tqdm
          playwright install chromium
          # تأكيد تثبيت المكتبات لضمان عدم حدوث ModuleNotFoundError
          pip list

      - name: Run Scraper
        run: python test2.py
        env:
          PYTHONUNBUFFERED: "1"
